### ISSUE TITLE
Confusing error message in UnitIsUsedWhenThereIsNoReturnValueForAFunction

### ISSUE THREAD

**Issue by relentless** [ChrisMarinos/FSharpKoans#24]
When this test fails, the message given is 'Expected: null'.

Looking at the code, I think what people are expected to put in is '()', but based on that message people often enter 'null', which also works but people find confusing.

Maybe if it's not possible to change the message, we could add a more explanatory comment or update the test in some way.

**Comment by dsyme** [comment]
Added comment to clarify this here: https://github.com/ChrisMarinos/FSharpKoans/pull/51
