### ISSUE TITLE
Confusing error message for TheTruthBehindMultipleReturnValues when integers entered

### ISSUE THREAD

**Issue by relentless** [ChrisMarinos/FSharpKoans#25]
I found that for the above koan, people often enter (9, 27) instead of (9.0, 27.0).  The trouble is, when they do this the error message reads:

Expected: <(9, 27)>
But was:  <(9, 27)>

Which has lead to some people getting stuck.  If the message can't be changed, perhaps a hint in a comment would help.

**Comment by ChrisMarinos** [comment]
This is one of the (unfortunate) consequences of #15. Until it's fixed, it's a good chance to have a discussion about equality in F#. :-)
