### ISSUE TITLE
VS 2015 error 'System.NullReferenceException' occurred in FSharpKoans.exe 

### ISSUE THREAD

**Issue by shek777** [ChrisMarinos/FSharpKoans#37]
Hello Sir,

Thanks for building this program. I got it working on VS 2013 perfectly, however when I run it on VS 2015 community edition I got this error on Helper.fs line 22 - "let AssertThrows<'a when 'a :> exn> action = Assert.Throws<'a>(fun () -> action())" error message "An exception of type 'System.NullReferenceException' occurred in FSharpKoans.exe but was not handled in user code"

I'm not sure how to fix it because I'm a novice in F# but love it.

Regards

**Comment by ChrisMarinos** [comment]
It might have something to do with exception settings- see #23 for more info.

**Comment by dsyme** [comment]
I agree this is the same cause as #23
