### ISSUE TITLE
Make suffix into a mutable

### ISSUE THREAD

**Issue by tbudurovych** [ChrisMarinos/FSharpKoans#41]
in https://github.com/ChrisMarinos/FSharpKoans/blob/fsharp/FSharpKoans/AboutFunctions.fs#L74 it says 

`(* TRY IT: What happens if you make suffix into a mutable variable? *)`

What is expected to happen? Doesn't seem to make any difference when I do `let mutable suffix = "!!!"`.

**Comment by ChrisMarinos** [comment]
Ah, sorry about that. As of F# 4.0, it won't do anything. In versions of F# prior to 4.0, that would have produced a compile error that told you that you couldn't capture a mutable variable inside of a closure. I'll remove the line from the koan.
