### ISSUE TITLE
Getting started with F# and Ionide

### ISSUE THREAD

**Issue by UncleFirefox** [ChrisMarinos/FSharpKoans#56]
Hey guys,

This project has been considered for a long time the entry point for a newbie in F# to get started with the language. Honestly I'd like to bootstrap the project using VSCode and Ionide as they are now a popular way to develop in F# but I get a lot of errors. Would it be too hard to make it work? Could you point me in the right direction?

Thanks!

**Comment by dsyme** [comment]
@UncleFirefox That sounds great - could you submit a PR for that?  I'm not sure why it's not working - perhaps it is a bug in Ionide?

**Comment by ChrisMarinos** [comment]
Closing the merge of #61
