### ISSUE TITLE
Running Koans on OS X command line

### ISSUE THREAD

**Issue by ArunParthiban10** [ChrisMarinos/FSharpKoans#59]
Is it possible to run the koans on OS X Command line? If so, could you please provide me with the instructions? When I try mono /usr/local/bin/nuget restore FSharpKoans.sln , I get an error saying 
"Cannot open assembly '/usr/local/bin/nuget': File does not contain a valid CIL image"

**Comment by baronfel** [comment]
On Mono, the `nuget` binary wrapper should be in your path, so you should just need to run `nuget restore FSharpKoans.sln`.  Can you try that to see if it works?

**Comment by jakzale** [comment]
As of of Mono 5.2.0.224 on OSX/macOS the `nuget` version is 2.12.0.0.

Running `nuget restore` will produce the following error:

```
$ nuget restore
Unable to find version '2.5.10.11092' of package 'NUnit'.
```

### Possible workaround
Download the [latest version](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) of nuget from [nuget.org](https://www.nuget.org)

```
$ wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
$ mono nuget.exe restore
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/15.0/bin/'.
Restoring NuGet package NUnit.2.5.10.11092.
Adding package 'NUnit.2.5.10.11092' to folder '/Users/jakub/Developer/FSharpKoans/packages'
Added package 'NUnit.2.5.10.11092' to folder '/Users/jakub/Developer/FSharpKoans/packages'

NuGet Config files used:
    /Users/jakub/Developer/FSharpKoans/.nuget/nuget.config
    /Users/jakub/.config/NuGet/NuGet.Config

Feeds used:
    /Users/jakub/.nuget/packages/
    https://api.nuget.org/v3/index.json
```

then you can build the koans using `msbuild`

```
$ msbuild
{ ... lots of text ... }

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:10.75
```

and then you can check/run the koans using `mono`

```
$ mono FSharpKoans/bin/Debug/FSharpKoans.exe
```

**Comment by ChrisMarinos** [comment]
#61 should hopefully address this!
