### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by MiloszKrajewski** [ChrisMarinos/FSharpKoans#66]
I've adapted FSharpKoans to .NET Core. You can find it [here](https://github.com/MiloszKrajewski/FSharpKoans). It won't support mono anymore though, so it is relatively large change.

Would like it to be kept separate, or would you accept pull request?

**Comment by ChrisMarinos** [comment]
Thanks for the comment. I think this is taken care of with the merge of #61, so feel free to give the .net core version a shot!
