### ISSUE TITLE
Incoherent error message in the 4th "koan"

### ISSUE THREAD

**Issue by urig** [ChrisMarinos/FSharpKoans#71]
I've completed the first three Koans successfully ("replace __ with ..." etc)
When I run the the project for the 4th koan (In VS Code with Ionide) I get the following stack trace:

I get:

    You have not yet reached enlightenment ...
      Expected: <System.String>
      But was:  <FSharpKoans.Core.Helpers+FILL_ME_IN>

    Please meditate on the following code:
       at NUnit.Framework.Assert.ReportFailure(String message)
       at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
       at FSharpKoans.Core.Helpers.AssertEquality[T](T x, T y) in C:\dev\ChrisMarinos\FSharpKoans\FSharpKoans.Core\Helpers.fs:line
17

The line referred to is:

    let AssertEquality (x:'T) (y:'T) = Assert.AreEqual(x,y)

in Helpers.fs

This is because I did not replace FILL_ME_IN with the "string".

Kindly requesting that the error message given be made clearer and point to the failed Koan and not to the helper as it's quite confusing for newbies.

**Comment by ChrisMarinos** [comment]
This should be fixed with #78 now.

**Comment by urig** [comment]
@ChrisMarinos, @sgoodgrove and @normanhh3 thank you!
