### ISSUE TITLE
AboutFunctions yelled.Trim()

### ISSUE THREAD

**Issue by gmotta** [ChrisMarinos/FSharpKoans#8]
Line 55 on AboutFunctions.fs

For some reason which I don't understand (I'm new to F#..), to end the let block you had to call yelled. <something>

You called yelled.Trim() which doesn't do anything and it doesn't make any sense for that context.

I would suggest changing it to ToString(), what do you say?

Also, it would be good to add a comment there explaining why it is required to end the let with a call to yelled. <something>

**Comment by voronoipotato** [comment]
No need for it to be ToString(), since text must be a string. If text had whitespace before it it would be removed. I feel like if this were the author's intent it might be better for the trim to be applied to text.

**Comment by dsyme** [comment]
Closing this very old issue
